import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Split('''
ble.c
''')

path = [
    cwd + '',
    ]

group = DefineGroup('COMPONENT_SDK', src, depend = [''], CPPPATH = path)

Return('group')

